@startuml

component core {
	package studit.core
	package studit.json
}

component jackson {
}

studit.json ..> jackson

component fxui {
	package studit.ui
}

studit.ui ..> studit.core
studit.ui ..> studit.json

component javafx {
	component fxml {
	}
}

fxui ..> javafx
fxui ..> fxml

component restapi {
	package studit.restapi
}

studit.restapi ..> studit.core
studit.restapi ..> studit.json

component jaxrs {
}

restapi ..> jaxrs

component restserver {
	package studit.restserver
}

studit.restserver ..> studit.core
studit.restserver ..> studit.restapi

component jersey {
}

component grizzly {
}

restserver ..> jersey
restserver ..> grizzly

@enduml
