@startuml
class CourseItem {
  - String fagnavn
  - String fagkode
  - String informasjon;
  - String pensumlitteratur;
  - String anbefaltLitteratur;
  - String tips;
  - String eksamensdato;
  - String vurderingsform;
  - String hjelpemidler;
  - float averageVurdering;
  - Discussion diskusjon;
}


class CourseController {
  - CourseItem courseItem
  - User currentUser

  + updateView()
  ~ openDiscussion()
  ~ handleMainPageAction()
  ~ openChatBot()
  ~ handleLogoutAction()

}


class DiscussionController {
    - CourseItem courseItem
    - ListView<Comment> forumList
    - User currentUser
    + RemoteStuditModelAcess remoteStuditModelAcess

    ~ addNewPost()
    + addCourse()
    + loadView()

    ~ handleMainPageAction()
    ~ openChatBot()
    ~ handleLogoutAction()

}

class Discussion {
    - Map<Integer, Comment> comments = 
    - int prevAssignedID = -1
}

class Comment {
    - String brukernavn;
    - String kommentar;
    -  String dato;
    -  int upvotes;
    -  int downvotes;
    -  int uniqueID;
    -  List<String> upvoters;
    -  List<String> downvoters;
}

class User {
    - String name;
    - String username;
    - String mail;
    - String password;
    - int uniqueID;
}

 
class AppController {
    - User currentUser
    - Chatbot chatbot
    - List<CourseItem> courseList
    - String label

    ~ openChatBot()
    + closeChatbot()
    + addUser()
    + loadData()
    + clickOnCourse()
}


class Chatbot{
    - Stage chatStage
    - ChatbotManager chatbotManager
    - ChatbotController controller

    - displayWindow()
    + show()
    + manageInput()
    + getController()
}

class ChatbotController {
    - Stage stage     
    + exitChatbot()
    + minimizeChatbot()
    + userEntry()
}

class RemoteStuditModelAcess {
    - StuditModel studitModel    
}



User <-- AppController: Authenticate through LoginController
AppController -- RemoteStuditModelAcess: uses >
ChatbotController -- RemoteStuditModelAcess: uses >
DiscussionController -- RemoteStuditModelAcess: uses >

AppController o-- "*" CourseItem: has >
AppController -- CourseController
AppController <-- DiscussionController
AppController --> Chatbot: opens >
Chatbot *-- "1" ChatbotController 

CourseItem *-- "1" Discussion: has >
DiscussionController -- CourseController
DiscussionController o-- "1" CourseItem
Discussion *-- "*" Comment: has >
CourseController o-- "1" CourseItem

@enduml